# Social Dilemma

> Class for a symmetric two-agent stateless social dilemma environment

Typical examples are the *Prisoner's Dilemma*, *Stag Hunt* game, and the game of *chicken*/*snowdrift*/*hawk-dove*.

In [ ]:
#| default_exp Environments/SocialDilemma

In [ ]:
#| hide
# Imports for the nbdev development environment
from nbdev.showdoc import *

In [ ]:
#| hide
%load_ext autoreload
%autoreload 2

In [ ]:
#| export
from pyCRLD.Environments.Base import ebase

from fastcore.utils import *
from fastcore.test import *

import numpy as np

In [ ]:
#| export
class SocialDilemma(ebase):
    """
    Symmetric 2-agent 2-action Social Dilemma Matrix Game.
    """ 

    def __init__(self,
                 R:float,  # reward of mutual cooperation
                 T:float,  # temptation of unilateral defection 
                 S:float,  # sucker's payoff of unilateral cooperation
                 P:float): # punsihment of mutual defection
        self.N = 2
        self.M = 2
        self.Z = 1

        self.Re = R
        self.Te = T
        self.Su = S    
        self.Pu = P

        self.state = 0 # inital state
        super().__init__()

In [ ]:
#| export
@patch
def TransitionTensor(self:SocialDilemma):
    """Get the Transition Tensor."""
    Tsas = np.ones((self.Z, self.M, self.M, self.Z))             
    return Tsas

In [ ]:
#| export
@patch
def RewardTensor(self:SocialDilemma):
    """Get the Reward Tensor R[i,s,a1,...,aN,s']."""

    R = np.zeros((2, self.Z, 2, 2, self.Z))

    R[0, 0, :, :, 0] = [[self.Re , self.Su],
                        [self.Te , self.Pu]]
    R[1, 0, :, :, 0] = [[self.Re , self.Te],
                        [self.Su , self.Pu]]

    return R

In [ ]:
#| export
@patch
def actions(self:SocialDilemma):
    """The action sets"""
    return [['c', 'd'] for _ in range(self.N)]

In [ ]:
#| export
@patch
def states(self:SocialDilemma):
    """The states set"""
    return ['.'] 

In [ ]:
#| export
@patch
def id(self:SocialDilemma):
    """
    Returns id string of environment
    """
    # Default
    id = f"{self.__class__.__name__}_"+\
        f"{self.Te}_{self.Re}_{self.Pu}_{self.Su}"
    return id


### Example

In [ ]:
env = SocialDilemma(R=1, T=2, S=-1, P=0)

In [ ]:
env.id()

'SocialDilemma_2_1_0_-1'

In [ ]:
env

SocialDilemma_2_1_0_-1

Reward matrix of agent `0`:

In [ ]:
env.RewardTensor()[0,0,:,:,0]

array([[ 1., -1.],
       [ 2.,  0.]])

Reward matrix of agent `1`:

In [ ]:
env.RewardTensor()[1,0,:,:,0]

array([[ 1.,  2.],
       [-1.,  0.]])

In [ ]:
env.TransitionTensor()

array([[[[1.],
         [1.]],

        [[1.],
         [1.]]]])

In [ ]:
env.actions()

[['c', 'd'], ['c', 'd']]

In [ ]:
env.states()

['.']

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()